version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    

  nompass_app:
    container_name: nompass_app
    restart: always
    build: ./nompass_app
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: gunicorn -w 1 -b :5000 main:app
    networks:
      - default
    links:
     - db:db
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
  
    networks:
      - default
    links:
      - nompass_app:nompass_app
  

volumes:
    postgres_data: